### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by Kadrian** [tessi/capistrano-uberspace#2]
Hi, thanks for the cool work!

To me, it didn't work without specifying `gem 'passenger'` and `gem 'unicorn'` in my Gemfile. Could you add that to Readme?

I wonder why passenger isn't picked up from the gem dependencies.

**Comment by tessi** [comment]
Hi @Kadrian,

sorry for the late response. I just figured out why passenger has to be installed separately.
If you put this gem in the development-group in your Gemfile, then the passenger (as a gem-dependency of this gem) will not be available in production.

Thanks for reporting! I will update the README
